.DEFAULT: all
.PHONY:
all: binutils-2.24.90.tar.bz2 cloog-0.18.1.tar.gz

binutils-2.24.90.tar.bz2:
	wget https://www.mirrorservice.org/sites/sourceware.org/pub/binutils/snapshots/binutils-2.24.90.tar.bz2

cloog-0.18.1.tar.gz:
	wget http://ftp.nluug.nl/languages/gcc/infrastructure/cloog-0.18.1.tar.gz
